export const productsHeroData = {
    eyebrow: "Products",
    title: "Produk digital Nexarin untuk kebutuhan kreator, brand, dan developer.",
    description:
        "Halaman Products disiapkan sebagai etalase produk digital by-rins: mulai dari template website, source code, AI workflow, sampai layanan custom build yang rapi, ringan, dan mobile-first.",
    primaryCta: {
        label: "Lihat Produk",
        href: "#products-market",
    },
    secondaryCta: {
        label: "Hubungi Nexarin",
        href: "/contact",
    },
    stats: [
        {
            value: "01",
            label: "Template",
        },
        {
            value: "02",
            label: "Source Code",
        },
        {
            value: "03",
            label: "Custom Build",
        },
    ],
};

export const productCategoriesPreview = [
    {
        title: "Website Template",
        label: "Template",
        status: "Coming Soon",
        description:
            "Template website modern untuk landing page, personal brand, company profile, dan kebutuhan digital ringan.",
    },
    {
        title: "Source Code Pack",
        label: "Code",
        status: "Planned",
        description:
            "Kumpulan source code siap dikembangkan ulang untuk mempercepat proses pembuatan project.",
    },
    {
        title: "Custom Digital Build",
        label: "Service",
        status: "Soon",
        description:
            "Layanan pembuatan halaman, sistem sederhana, dashboard, atau kebutuhan digital custom.",
    },
];

export const productMarketplaceData = {
    categories: [
        {
            label: "Semua",
            slug: "semua",
            icon: "✦",
            description: "Semua produk digital Nexarin.",
        },
        {
            label: "AI Tools",
            slug: "ai-tools",
            icon: "🤖",
            description: "Prompt, workflow, dan kit kerja berbasis AI.",
        },
        {
            label: "PPOB",
            slug: "ppob",
            icon: "⚡",
            description: "Starter tampilan untuk produk pembayaran digital.",
        },
        {
            label: "Fashion",
            slug: "fashion",
            icon: "👕",
            description: "UI dan asset visual untuk katalog fashion.",
        },
        {
            label: "Ebook",
            slug: "ebook",
            icon: "📚",
            description: "Landing page dan layout untuk produk edukasi digital.",
        },
    ],

    products: [
        {
            slug: "nexarin-ai-prompt-pack",
            title: "Nexarin AI Prompt Pack",
            category: "AI Tools",
            categorySlug: "ai-tools",
            type: "Prompt Pack",
            status: "Ready Preview",
            oldPrice: "Rp 299.000",
            price: "Rp 149.000",
            rating: "4.9",
            icon: "🤖",
            accent: "emerald",
            image: "",
            delivery: "File digital",
            bestFor: "Creator, UMKM, personal brand",
            description:
                "Paket prompt premium untuk membantu pembuatan konten, ide produk, copywriting, dan workflow digital.",
            features: [
                "Prompt siap pakai",
                "Alur kerja konten",
                "Struktur ide produk",
            ],
        },
        {
            slug: "ai-content-assistant-kit",
            title: "AI Content Assistant Kit",
            category: "AI Tools",
            categorySlug: "ai-tools",
            type: "Workflow Kit",
            status: "Ready Preview",
            oldPrice: "Rp 249.000",
            price: "Rp 129.000",
            rating: "4.8",
            icon: "✍️",
            accent: "cyan",
            image: "",
            delivery: "File digital",
            bestFor: "Content creator, marketer",
            description:
                "Kit prompt dan template kerja untuk mempercepat proses riset, penulisan, dan produksi konten.",
            features: [
                "Template riset konten",
                "Outline artikel",
                "Prompt copywriting",
            ],
        },
        {
            slug: "ppob-landing-starter",
            title: "PPOB Landing Starter",
            category: "PPOB",
            categorySlug: "ppob",
            type: "Landing Starter",
            status: "Prototype",
            oldPrice: "Rp 399.000",
            price: "Rp 199.000",
            rating: "4.8",
            icon: "⚡",
            accent: "emerald",
            image: "",
            delivery: "Source UI",
            bestFor: "Pulsa, paket data, tagihan",
            description:
                "Starter tampilan halaman PPOB untuk produk pulsa, paket data, tagihan, dan layanan digital.",
            features: [
                "Hero produk digital",
                "Section layanan",
                "CTA order manual",
            ],
        },
        {
            slug: "digital-payment-ui-kit",
            title: "Digital Payment UI Kit",
            category: "PPOB",
            categorySlug: "ppob",
            type: "UI Kit",
            status: "Prototype",
            oldPrice: "Rp 349.000",
            price: "Rp 179.000",
            rating: "4.7",
            icon: "💳",
            accent: "cyan",
            image: "",
            delivery: "Design + UI",
            bestFor: "Checkout, billing, top up",
            description:
                "UI kit halaman pembayaran digital dengan tampilan mobile-first dan alur checkout sederhana.",
            features: [
                "Card pembayaran",
                "Ringkasan order",
                "Layout mobile-first",
            ],
        },
        {
            slug: "fashion-store-card-ui",
            title: "Fashion Store Card UI",
            category: "Fashion",
            categorySlug: "fashion",
            type: "Card UI",
            status: "Draft UI",
            oldPrice: "Rp 199.000",
            price: "Rp 99.000",
            rating: "4.7",
            icon: "👕",
            accent: "emerald",
            image: "",
            delivery: "Component UI",
            bestFor: "Katalog, promo, marketplace",
            description:
                "Template card produk fashion untuk katalog, promo, dan etalase produk online.",
            features: [
                "Card katalog",
                "Badge promo",
                "CTA detail produk",
            ],
        },
        {
            slug: "fashion-promo-banner-pack",
            title: "Fashion Promo Banner Pack",
            category: "Fashion",
            categorySlug: "fashion",
            type: "Banner Pack",
            status: "Draft UI",
            oldPrice: "Rp 229.000",
            price: "Rp 119.000",
            rating: "4.8",
            icon: "🏷️",
            accent: "cyan",
            image: "",
            delivery: "Asset digital",
            bestFor: "Campaign, promo, katalog",
            description:
                "Paket banner promo fashion dengan style modern untuk halaman marketplace dan campaign.",
            features: [
                "Hero promo",
                "Banner campaign",
                "Layout responsive",
            ],
        },
        {
            slug: "ebook-landing-template",
            title: "Ebook Landing Template",
            category: "Ebook",
            categorySlug: "ebook",
            type: "Landing Page",
            status: "Ready Preview",
            oldPrice: "Rp 199.000",
            price: "Rp 89.000",
            rating: "4.8",
            icon: "📚",
            accent: "emerald",
            image: "",
            delivery: "Template page",
            bestFor: "Ebook, modul, panduan",
            description:
                "Template landing page untuk menjual ebook, modul digital, panduan, atau produk edukasi.",
            features: [
                "Hero ebook",
                "Benefit section",
                "CTA pembelian",
            ],
        },
        {
            slug: "digital-ebook-layout-kit",
            title: "Digital Ebook Layout Kit",
            category: "Ebook",
            categorySlug: "ebook",
            type: "Layout Kit",
            status: "Ready Preview",
            oldPrice: "Rp 249.000",
            price: "Rp 129.000",
            rating: "4.9",
            icon: "📖",
            accent: "cyan",
            image: "",
            delivery: "Layout section",
            bestFor: "Preview ebook, daftar isi",
            description:
                "Layout kit untuk halaman preview ebook, daftar isi, benefit, testimoni, dan tombol pembelian.",
            features: [
                "Preview konten",
                "Daftar isi",
                "Testimoni section",
            ],
        },
    ],
};