from fastapi import APIRouter, File, UploadFile, HTTPException
from fastapi.responses import FileResponse
import subprocess
import tempfile
import os
import time
import random

router = APIRouter()

@router.post("/convert/word-to-pdf")
async def convert_word_to_pdf(file: UploadFile = File(...)):
    valid_extensions = ('.doc', '.docx')
    if not file.filename.lower().endswith(valid_extensions):
        raise HTTPException(status_code=400, detail="File must be a Word document")
    
    unique_id = f"{int(time.time())}_{random.randint(1000, 9999)}"
    temp_dir = tempfile.gettempdir()
    
    safe_name = f"input_{unique_id}.docx"
    input_docx = os.path.join(temp_dir, safe_name)
    expected_output_pdf = os.path.join(temp_dir, f"input_{unique_id}.pdf")
    
    try:
        with open(input_docx, "wb") as buffer:
            content = await file.read()
            buffer.write(content)
            
        subprocess.run([
            'libreoffice', '--headless', '--convert-to', 'pdf', '--outdir', temp_dir, input_docx
        ], check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        
        if not os.path.exists(expected_output_pdf):
            raise Exception("PDF file was not generated by LibreOffice")
            
        return FileResponse(
            expected_output_pdf, 
            media_type="application/pdf",
            filename=f"{file.filename.rsplit('.', 1)[0]}_nexarin.pdf"
        )
    except Exception as e:
        print(f"Word to PDF error: {e}")
        raise HTTPException(status_code=500, detail=str(e))
    finally:
        if os.path.exists(input_docx):
            try: os.remove(input_docx)
            except: pass
