import { 
  FilePlus2, SplitSquareHorizontal, Zap, FileText, Presentation, Table, 
  Image as ImageIcon, Edit3, PenTool, Stamp, RotateCw, Globe, 
  Unlock, ShieldCheck, Layers, Archive, Wrench, Hash, Scan, 
  FileSearch, Split, Scissors, FormInput, Sparkles, Languages, 
  Code, Network 
} from "lucide-react";

export const pdfTools = [
  {
    id: "merge",
    title: "Merge PDF",
    description: "Combine PDFs in the order you want with the easiest PDF merger available.",
    icon: FilePlus2,
    color: "text-red-400",
    bgColor: "bg-red-500/10",
    isActive: false,
  },
  {
    id: "split",
    title: "Split PDF",
    description: "Separate one page or a whole set for easy conversion into independent PDF files.",
    icon: SplitSquareHorizontal,
    color: "text-orange-400",
    bgColor: "bg-orange-500/10",
    isActive: false,
  },
  {
    id: "compress",
    title: "Compress PDF",
    description: "Reduce file size while optimizing for maximal PDF quality.",
    icon: Zap,
    color: "text-green-400",
    bgColor: "bg-green-500/10",
    isActive: true,
  },
  {
    id: "pdf-to-word",
    title: "PDF to Word",
    description: "Easily convert your PDF files into easy to edit DOC and DOCX documents.",
    icon: FileText,
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
    isActive: true,
  },
  {
    id: "pdf-to-powerpoint",
    title: "PDF to PowerPoint",
    description: "Turn your PDF files into easy to edit PPT and PPTX slideshows.",
    icon: Presentation,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
    isActive: false,
  },
  {
    id: "pdf-to-excel",
    title: "PDF to Excel",
    description: "Pull data straight from PDFs into Excel spreadsheets in a few short seconds.",
    icon: Table,
    color: "text-emerald-400",
    bgColor: "bg-emerald-500/10",
    isActive: true,
  },
  {
    id: "word-to-pdf",
    title: "Word to PDF",
    description: "Make DOC and DOCX files easy to read by converting them to PDF.",
    icon: FileText,
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
    isActive: true,
  },
  {
    id: "powerpoint-to-pdf",
    title: "PowerPoint to PDF",
    description: "Make PPT and PPTX slideshows easy to view by converting them to PDF.",
    icon: Presentation,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
    isActive: false,
  },
  {
    id: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Make EXCEL spreadsheets easy to read by converting them to PDF.",
    icon: Table,
    color: "text-emerald-400",
    bgColor: "bg-emerald-500/10",
    isActive: false,
  },
  {
    id: "edit",
    title: "Edit PDF",
    description: "Add text, images, shapes or freehand annotations to a PDF document.",
    icon: Edit3,
    color: "text-purple-400",
    bgColor: "bg-purple-500/10",
    isActive: true,
  },
  {
    id: "pdf-to-png",
    title: "PDF to PNG",
    description: "Convert each PDF page into a PNG or extract all images contained in a PDF.",
    icon: ImageIcon,
    color: "text-yellow-400",
    bgColor: "bg-yellow-500/10",
    isActive: true,
  },
  {
    id: "jpg-to-pdf",
    title: "JPG to PDF",
    description: "Convert JPG images to PDF in seconds. Easily adjust orientation and margins.",
    icon: ImageIcon,
    color: "text-yellow-400",
    bgColor: "bg-yellow-500/10",
    isActive: true,
  },
  {
    id: "sign",
    title: "Sign PDF",
    description: "Sign yourself or request electronic signatures from others.",
    icon: PenTool,
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
  },
  {
    id: "watermark",
    title: "Watermark",
    description: "Stamp an image or text over your PDF in seconds. Choose the typography, transparency and position.",
    icon: Stamp,
    color: "text-pink-400",
    bgColor: "bg-pink-500/10",
  },
  {
    id: "rotate",
    title: "Rotate PDF",
    description: "Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once!",
    icon: RotateCw,
    color: "text-purple-400",
    bgColor: "bg-purple-500/10",
  },
  {
    id: "html-to-pdf",
    title: "HTML to PDF",
    description: "Convert webpages in HTML to PDF. Copy and paste the URL of the page you want and convert it.",
    icon: Globe,
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10",
  },
  {
    id: "unlock",
    title: "Unlock PDF",
    description: "Remove PDF password security, giving you the freedom to use your PDFs as you want.",
    icon: Unlock,
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
  },
  {
    id: "protect",
    title: "Protect PDF",
    description: "Protect PDF files with a password. Encrypt PDF documents to prevent unauthorized access.",
    icon: ShieldCheck,
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
  },
  {
    id: "organize",
    title: "Organize PDF",
    description: "Sort pages of your PDF file however you like. Delete PDF pages or add PDF pages to your document.",
    icon: Layers,
    color: "text-red-400",
    bgColor: "bg-red-500/10",
  },
  {
    id: "pdf-to-pdfa",
    title: "PDF to PDF/A",
    description: "Transform your PDF to PDF/A, the ISO-standardized version of PDF for long-term archiving.",
    icon: Archive,
    color: "text-slate-400",
    bgColor: "bg-slate-500/10",
  },
  {
    id: "repair",
    title: "Repair PDF",
    description: "Repair a damaged PDF and recover data from corrupt PDF. Fix PDF files with our Repair tool.",
    icon: Wrench,
    color: "text-green-400",
    bgColor: "bg-green-500/10",
  },
  {
    id: "page-numbers",
    title: "Page numbers",
    description: "Add page numbers into PDFs with ease. Choose your positions, dimensions, typography.",
    icon: Hash,
    color: "text-pink-400",
    bgColor: "bg-pink-500/10",
  },
  {
    id: "scan",
    title: "Scan to PDF",
    description: "Capture document scans from your mobile device and send them instantly to your browser.",
    icon: Scan,
    color: "text-red-400",
    bgColor: "bg-red-500/10",
  },
  {
    id: "ocr",
    title: "OCR PDF",
    description: "Easily convert scanned PDF into searchable and selectable documents.",
    icon: FileSearch,
    color: "text-green-400",
    bgColor: "bg-green-500/10",
  },
  {
    id: "compare",
    title: "Compare PDF",
    description: "Show a side-by-side document comparison and easily spot changes between different file versions.",
    icon: Split,
    color: "text-indigo-400",
    bgColor: "bg-indigo-500/10",
  },
  {
    id: "redact",
    title: "Redact PDF",
    description: "Redact text and graphics to permanently remove sensitive information from a PDF.",
    icon: Scissors,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
  },
  {
    id: "crop",
    title: "Crop PDF",
    description: "Crop margins of PDF documents or select specific areas, then apply the changes to one page or the whole document.",
    icon: Scissors,
    color: "text-pink-500",
    bgColor: "bg-pink-500/10",
  },
  {
    id: "forms",
    title: "PDF Forms",
    description: "Detect form fields automatically, create interactive fillable PDFs, or fill PDF forms yourself.",
    icon: FormInput,
    color: "text-purple-400",
    bgColor: "bg-purple-500/10",
    isNew: true,
  },
  {
    id: "ai-summarizer",
    title: "AI Summarizer",
    description: "Quickly generate concise summaries from articles, paragraphs, and essays, providing clear and precise key points in seconds.",
    icon: Sparkles,
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
    isNew: true,
  },
  {
    id: "translate",
    title: "Translate PDF",
    description: "Easily translate PDF files powered by AI. Keep fonts, layout, and formatting perfectly intact.",
    icon: Languages,
    color: "text-indigo-400",
    bgColor: "bg-indigo-500/10",
    isNew: true,
  },
  {
    id: "markdown",
    title: "PDF to Markdown",
    description: "Easily turn PDFs into Markdown files. Perfect for notes, docs, and LLMs. Headings, tables, lists, and links preserved automatically.",
    icon: Code,
    color: "text-purple-400",
    bgColor: "bg-purple-500/10",
    isNew: true,
  },
];
