import { 
  FilePlus2, SplitSquareHorizontal, Zap, FileText, Presentation, Table, 
  Image as ImageIcon, Edit3, PenTool, Stamp, RotateCw, Globe, 
  Unlock, ShieldCheck, Layers, Archive, Wrench, Hash, Scan, 
  FileSearch, Split, Scissors, FormInput, Sparkles, Languages, 
  Code, Network 
} from "lucide-react";

export const pdfTools = [
  {
    id: "merge",
    title: "Merge PDF",
    description: "Gabungkan beberapa PDF sesuai urutan yang Anda inginkan dengan mudah dan cepat.",
    icon: FilePlus2,
    color: "text-red-400",
    bgColor: "bg-red-500/10",
    isActive: true,
  },
  {
    id: "split",
    title: "Split PDF",
    description: "Pisahkan satu halaman atau seluruh dokumen untuk konversi mudah menjadi file PDF terpisah.",
    icon: SplitSquareHorizontal,
    color: "text-orange-400",
    bgColor: "bg-orange-500/10",
    isActive: true,
  },
  {
    id: "compress",
    title: "Compress PDF",
    description: "Kurangi ukuran file dokumen Anda tanpa mengurangi kualitas PDF secara maksimal.",
    icon: Zap,
    color: "text-green-400",
    bgColor: "bg-green-500/10",
    isActive: true,
  },
  {
    id: "pdf-to-word",
    title: "PDF to Word",
    description: "Ubah file PDF Anda menjadi dokumen Word (DOC/DOCX) yang mudah diedit.",
    icon: FileText,
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
    isActive: true,
  },
  {
    id: "pdf-to-powerpoint",
    title: "PDF to PowerPoint",
    description: "Ubah file PDF Anda menjadi presentasi PPT dan PPTX yang siap disunting.",
    icon: Presentation,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
    isActive: true,
  },
  {
    id: "pdf-to-excel",
    title: "PDF to Excel",
    description: "Tarik data langsung dari dokumen PDF ke dalam spreadsheet Excel hanya dalam hitungan detik.",
    icon: Table,
    color: "text-emerald-400",
    bgColor: "bg-emerald-500/10",
    isActive: true,
  },
  {
    id: "word-to-pdf",
    title: "Word to PDF",
    description: "Jadikan file dokumen DOC dan DOCX lebih mudah dibaca dengan mengubahnya menjadi PDF.",
    icon: FileText,
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
    isActive: true,
  },
  {
    id: "powerpoint-to-pdf",
    title: "PowerPoint to PDF",
    description: "Buat tayangan slide presentasi Anda lebih mudah dilihat dengan mengubahnya menjadi PDF.",
    icon: Presentation,
    color: "text-orange-500",
    bgColor: "bg-orange-500/10",
    isActive: true,
  },
  {
    id: "excel-to-pdf",
    title: "Excel to PDF",
    description: "Buat tabel EXCEL Anda lebih mudah dibaca dan dibagikan dengan mengubahnya menjadi PDF.",
    icon: Table,
    color: "text-emerald-400",
    bgColor: "bg-emerald-500/10",
    isActive: true,
  },
  {
    id: "edit",
    title: "Edit PDF",
    description: "Tambahkan teks, gambar, bentuk, atau coretan anotasi bebas ke dokumen PDF Anda.",
    icon: Edit3,
    color: "text-purple-400",
    bgColor: "bg-purple-500/10",
    isActive: true,
  },
  {
    id: "pdf-to-png",
    title: "PDF to PNG",
    description: "Ubah setiap halaman dokumen PDF menjadi gambar PNG atau ekstrak seluruh gambarnya.",
    icon: ImageIcon,
    color: "text-yellow-400",
    bgColor: "bg-yellow-500/10",
    isActive: true,
  },
  {
    id: "jpg-to-pdf",
    title: "JPG to PDF",
    description: "Ubah gambar JPG menjadi PDF dalam hitungan detik. Atur orientasi dan margin dengan mudah.",
    icon: ImageIcon,
    color: "text-yellow-400",
    bgColor: "bg-yellow-500/10",
    isActive: true,
  },
  {
    id: "sign",
    title: "Sign PDF",
    description: "Tanda tangani sendiri dokumen Anda atau minta tanda tangan elektronik dari orang lain.",
    icon: PenTool,
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
    isActive: true,
  },
  {
    id: "watermark",
    title: "Watermark",
    description: "Cap gambar atau teks di atas PDF Anda secara instan. Atur tipografi, transparansi, dan posisi.",
    icon: Stamp,
    color: "text-pink-400",
    bgColor: "bg-pink-500/10",
    isActive: true,
  },
  {
    id: "rotate",
    title: "Rotate PDF",
    description: "Putar halaman PDF sesuai keinginan Anda. Anda bahkan bisa memutar banyak PDF sekaligus!",
    icon: RotateCw,
    color: "text-purple-400",
    bgColor: "bg-purple-500/10",
    isActive: true,
  },
  {
    id: "html-to-pdf",
    title: "HTML to PDF",
    description: "Ubah halaman web HTML menjadi PDF. Cukup salin dan tempel URL halaman yang ingin dikonversi.",
    icon: Globe,
    color: "text-cyan-400",
    bgColor: "bg-cyan-500/10",
    isActive: true,
  },
  {
    id: "unlock",
    title: "Unlock PDF",
    description: "Hapus kata sandi keamanan PDF, memberi Anda kebebasan penuh untuk menggunakan dokumen Anda.",
    icon: Unlock,
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
    isActive: true,
  },
  {
    id: "protect",
    title: "Protect PDF",
    description: "Lindungi dokumen PDF dengan kata sandi. Enkripsi PDF untuk mencegah akses tidak sah.",
    icon: ShieldCheck,
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
    isActive: true,
  },
  {
    id: "organize",
    title: "Organize PDF",
    description: "Susun halaman file PDF sesuka Anda. Hapus halaman atau tambahkan halaman baru ke dokumen.",
    icon: Layers,
    color: "text-red-400",
    bgColor: "bg-red-500/10",
    isActive: true,
  },
  {
    id: "pdf-to-pdfa",
    title: "PDF to PDF/A",
    description: "Ubah PDF Anda ke PDF/A, versi standar ISO dari PDF untuk pengarsipan jangka panjang.",
    icon: Archive,
    color: "text-slate-400",
    bgColor: "bg-slate-500/10",
    isActive: true,
  },
  {
    id: "repair",
    title: "Repair PDF",
    description: "Perbaiki PDF yang rusak dan pulihkan data dari file yang korup dengan alat Perbaikan kami.",
    icon: Wrench,
    color: "text-green-400",
    bgColor: "bg-green-500/10",
    isActive: true,
  },
  {
    id: "page-numbers",
    title: "Page numbers",
    description: "Tambahkan nomor halaman ke PDF dengan mudah. Pilih posisi, dimensi, dan tipografinya.",
    icon: Hash,
    color: "text-pink-400",
    bgColor: "bg-pink-500/10",
    isActive: true,
  },
  {
    id: "scan",
    title: "Scan to PDF",
    description: "Tangkap pindaian dokumen dari perangkat seluler Anda dan kirim langsung ke browser Anda.",
    icon: Scan,
    color: "text-red-400",
    bgColor: "bg-red-500/10",
    isActive: true,
  },
  {
    id: "ocr",
    title: "OCR PDF",
    description: "Ubah file PDF hasil pindaian (scan) menjadi dokumen teks yang dapat dicari dan dipilih dengan mudah.",
    icon: FileSearch,
    color: "text-green-400",
    bgColor: "bg-green-500/10",
    isActive: true,
  },
  {
    id: "compare",
    title: "Compare PDF",
    description: "Tampilkan perbandingan dokumen berdampingan dan temukan perubahan dengan mudah.",
    icon: Split,
    color: "text-indigo-400",
    bgColor: "bg-indigo-500/10",
    isActive: true,
  },
  {
    id: "redact",
    title: "Redact PDF",
    description: "Sensor teks dan grafis untuk menghapus informasi sensitif dari dokumen PDF secara permanen.",
    icon: Scissors,
    color: "text-blue-500",
    bgColor: "bg-blue-500/10",
    isActive: true,
  },
  {
    id: "crop",
    title: "Crop PDF",
    description: "Potong margin dokumen PDF atau pilih area tertentu, lalu terapkan perubahan tersebut.",
    icon: Scissors,
    color: "text-pink-500",
    bgColor: "bg-pink-500/10",
    isActive: true,
  },
  {
    id: "forms",
    title: "PDF Forms",
    description: "Deteksi kolom formulir secara otomatis, buat PDF interaktif, atau isi formulir PDF sendiri.",
    icon: FormInput,
    color: "text-purple-400",
    bgColor: "bg-purple-500/10",
    isNew: true,
    isActive: true,
  },
  {
    id: "ai-summarizer",
    title: "AI Summarizer",
    description: "Hasilkan ringkasan singkat dari artikel secara cepat, memberikan poin utama yang tepat dan jelas.",
    icon: Sparkles,
    color: "text-blue-400",
    bgColor: "bg-blue-500/10",
    isNew: true,
  },
  {
    id: "translate",
    title: "Translate PDF",
    description: "Terjemahkan file PDF dengan mudah didukung oleh AI. Pertahankan font, tata letak, dan format asli.",
    icon: Languages,
    color: "text-indigo-400",
    bgColor: "bg-indigo-500/10",
    isNew: true,
    isActive: true,
  },
  {
    id: "markdown",
    title: "PDF to Markdown",
    description: "Ubah PDF menjadi file Markdown dengan mudah. Tajuk, tabel, daftar, dan tautan dipertahankan.",
    icon: Code,
    color: "text-purple-400",
    bgColor: "bg-purple-500/10",
    isNew: true,
    isActive: true,
  },
];
